Update corpus
QuantGov/documentation pull request #9
Opened 2017-12-04 19:33 UTC by jnelson16

2018-01-12 19:34 UTC, OliverSherouse requested changes

2018-01-12 19:34 UTC, OliverSherouse commented on docs/corpus.markdown
>  The names of the components of the index are stored in a module-level constant named `INDEX`, and are always a tuple, even when the index only has one component. Thus, for the CFR, `INDEX = ('year',
This isn't actually true any more; now the index labels are either passed to the driver constructor or identified by the column names or regex pattern

2018-01-12 19:34 UTC, OliverSherouse commented on docs/corpus.markdown
> +- **Recursive directory corpus driver** serves a corpus with files organized in a recursive directory. The index labels are defined by the user in the driver and the index values are the names of the
Man, I should change this name to something like FolderIndexDriver, shouldn't I? It's not the directory itself that's recursive. The driver descends into the directory recursively.

2018-01-12 19:34 UTC, OliverSherouse commented on docs/corpus.markdown
> +    pattern=r'(?P<year>\d{4})-(?P<title>\d{1,})-(?P<part>\d{1,})'
Should be \d+ for title and part, I think

2018-01-12 19:34 UTC, OliverSherouse commented on docs/corpus.markdown
> +Relevant metadata will vary from corpus to corpus. Metadata can be generated from one of two sources: from the text itself or from additional external information. In the first case, the best practic
We should get rid of the references to get_wordcount and get_restriction_count.py, since they no longer exist

2018-01-12 19:34 UTC, OliverSherouse commented on docs/corpus.markdown
> +
Can you add a bit on how to call these?

2018-01-16 16:37 UTC, jnelson16 commented
Should be ready for a second look

2018-09-28 19:26 UTC, closed without merging